version = "1.0"
[main]
    name.en = "configuration"
    name.de = "Konfiguration"
    [main.notifications]
        name.en = "email notifications"
        name.de = "E-Mail Benachrichtigungen"
        [main.notifications.admin_mail]
        type = "email"
        ask.en = "recipient of notifications"
        help.en = "this email gets notified about events like changes in the user database of flohmarkt"
        ask.de = "Empfänger von Benachrichtigungen"
        help.de = "an diese E-Mail Adresse werden Informationen zu z.B. Änderungen an der Benutzerdatenbank geschickt"
        bind = "email>to:__INSTALL_DIR__/urlwatch/config.yaml"

    [main.flohmarkt]
        name.en = "flohmarkt settings"
        name.de = "flohmarkt Konfiguration"
        [main.flohmarkt.flohmarkt_initial_setup_url]
        type = "text"
        readonly = true
        ask.en = "initial setup"
        ask.de = "Initiales Setup"
        help.en = "open this url to finish your flohmarkt setup"
        help.de = "öffne die URL um flohmarkt fertig zu konfigurieren"

#[flohmarkt_setup]
#    name = "setup"
#    [flohmarkt_setup.flohmarkt_initial_setup_url]
#        name = "initial setup url"
#        type = "string"
#        ask = "open this url to initially setup flohmarkt"
#        help = "you can't change this value"
