#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "flohmarkt"
name = "flohmarkt"
description.en = "A decentral federated small ads platform"

version = "1.0~ynh1"

maintainers = ["Chris Vogel"]

[upstream]
license = "AGPL-3.0"
website = "https://codeberg.org/flohmarkt/flohmarkt"
demo = "https://flohmarkt.ween.de/"
admindoc = "https://codeberg.org/flohmarkt/flohmarkt/wiki"
userdoc = "https://codeberg.org/flohmarkt/flohmarkt/wiki"
code = "https://codeberg.org/flohmarkt/flohmarkt"
# For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
# cpe = "does_not_exist_yet"

# This is meant to be an URL where people can financially support this app, especially when its development is based
# on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.
# fund = "???"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true

# the "ldap" key corresponds to wether or not a user *can* login on the app using
# its YunoHost credentials.
# https://codeberg.org/ChriChri/flohmarkt_ynh/issues/2
ldap = "false"

# the "sso" key corresponds to wether or not a user is *automatically logged-in*
# on the app when logged-in on the YunoHost portal.
# "Internally, SSOwat will on-the-fly inject HTTP Basic Auth Headers like Authorization: 
# Basic <base64credentials>."
# https://yunohost.org/de/packaging_sso_ldap_integration#sso-integration
# https://codeberg.org/ChriChri/flohmarkt_ynh/issues/3
sso = "false"

# FIXME: replace with an **estimate** minimum disk and RAM requirements. e.g. 20M, 400M, 1G...
disk = "10M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    # ask admin on which domain to run flohmarkt
    type = "domain"

# https://codeberg.org/ChriChri/flohmarkt_ynh/issues/4
#     [install.path]
#     # ask admin under which path flohmarkt will be reachable
#     # e.g. 'https://doma.in/path' - might not work, needs to be tested:
#     # https://codeberg.org/ChriChri/flohmarkt_ynh/issues/4
#     type = "path"
#     default = "/"

    [install.init_main_permission]
    # who will be able to access the apps URL after installation?
    type = "group"
    default = "visitors"

    [install.password_couchdb_admin]
    # couchdb admin password
    type = "password"
    ask.en = "CouchDB password for admin user"
    help.en = "Don't forget to note this password somewhere! You need to provide this password during install and for future upgrades. If there's already a CouchDB installed provide the adminpassword for the existing installation."
    ask.de = "Passwort für den admin Benutzer von CouchDB"
    help.de = "Bitte das Passwort notieren und aufheben! Dieses Passwort muss bei der Installation und bei zukünftigen Upgrades eingegeben werden. Wenn bereits eine CouchDB installiert ist, hier das Passwort der bestehenden Installation eingeben."

    [install.password_couchdb_flohmarkt]
    # cochdb flohmarkt user password
    type = "password"
    ask.en = "CouchDB password for flohmarkt user"
    help.en = "This password will be used by flohmarkt during normal operation and is stored in its configuration file flohmarkt.conf"
    ask.de = "Passwort für den admin Benutzer von CouchDB"
    help.de = "Dieses Passwort wird von flohmarkt im normalen Betrieb verwendet und ist in der Konfigurationsdatei flohmarkt.conf gespeichert."

    [install.mail_user]
    # @@ any type for this to make sure it can be used as the user part of an email address?
    default = "flohmarkt"
    ask.en = "mail sender local part"
    help.en = "flohmarkt will send emails using the sender <mail_user>@<mail_domain>. Please provide the <mail_user> part."
    ask.de = "E-Mail-Absender Benutzername"
    help.de = "flohmarkt verschickt emails unter dem Absender <mail_user>@<mail_domain>. Bitte gib Deinen <mail_user> ein."

    [install.mail_domain]
    # @@ is there a 'type' that makes sure that on this domain email service is enabled?
    type = "domain"
    ask.en = "mail sender domain part"
    help.en = "flohmarkt will send emails using the sender <mail_user>@<mail_domain>. Please provide the <mail_domain> part."
    ask.de = "E-Mail-Absender Domain"
    help.de = "flohmarkt verschickt emails unter dem Absender <mail_user>@<mail_domain>. Bitte gib Deine <mail_domain> ein."

    [install.flohmarkt_name]
    # flohmarkt.conf: "InstanceName"
    default = "my yunohost flohmarkt"
    ask.en = "name of your flohmarkt instance"
    ask.de = "Name des Flohmarkts"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

    [resources.sources.main]
    # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
    #    ynh_setup_source --dest_dir="$install_dir"
    # You can also define other assets than "main" and add --source_id="foobar" in the previous command
    url = "https://codeberg.org/flohmarkt/flohmarkt/archive/490a748cc3a6698c8a6400df3fa9cfdcf4fd76da.tar.gz"
    sha256 = "45d40fb96c9997502755939d0ba6bac9df39d3ca30d271be01b69202b88839fb"

    # These infos are used by https://github.com/YunoHost/apps/blob/master/tools/autoupdate_app_sources/autoupdate_app_sources.py
    # to auto-update the previous asset urls and sha256sum + manifest version
    # assuming the upstream's code repo is on github and relies on tags or releases
    # See the 'sources' resource documentation for more details

    # autoupdate.strategy = "latest_github_tag"

    # This will provision/deprovision a unix system user named id form above → 'flohmarkt'
    [resources.system_user]
    allow_email = true
    # ++ where to get/put mail_user and mail_domain to let the user set the address?
    #    https://yunohost.org/de/packaging_apps_resources#properties-4
    #    → [install] section
    # these shouldn't be necessary, because defined in the [install] section
    #    → yes, works. With the values from install section the mailuser ends up in 
    #      /etc/postfix/app_senders_login_maps
    # mail_user = "replace_mail_user_in_manifest_toml"
    # mail_domain = "replace_mail_domain_in_manifest.toml"
    # @@ how to create a couchdb user if needed? in install-script manually?

    [resources.install_dir]
    dir = "/opt/flohmarkt"

    [resources.data_dir]
    # This will create/remove the data dir as /home/yunohost.app/$app
    # and store the corresponding setting $data_dir

    [resources.permissions]
    # This will configure SSOwat permission for $domain/$path/
    # The initial allowed group of user is configured via the init_main_permission question 
    # (public=visitors, private=all_users)
    # https://codeberg.org/ChriChri/flohmarkt_ynh/issues/5
    main.url = "/"

    [resources.ports]
    # This will pick a random port for reverse-proxying and store it as the $port setting
    # uvicorn running the flohmarkt app will be started listening to this port
    # if 'main.default' is already in use another random port will be used
    main.default = 8000
    couchdb.default = 5984
    

    [resources.apt]
    # python dependencies shall be installed in a venv using pip.
    packages = "python3-pip python3-full curl apt-transport-https gnupg"

[antifeatures]

[alpha-software]
description.en = "Early development stage. May contain changing or unstable features, bugs, and security vulnerability."
description.eu = "Garapenaren hasierako fasean dago. Ezaugarri aldakor edo ezegonkorrak, erroreak eta segurtasuneko arazoak izan ditzazke."
description.fr = "Le logiciel est au tout début de son développement. Il pourrait contenir des fonctionnalités changeantes ou instables, des bugs, et des failles de sécurité."
description.it = "Questo software è all’inizio della sua fase di sviluppo. Potrebbe dunque essere instabile, contenere bug e vulnerabilità di sicurezza."
icon = "flask"
title.en = "Alpha software"
title.eu = "Alfa softwarea"
title.fr = "Logiciel en version alpha "
title.it = "Software in versione alpha"

[arbitrary-limitations]
title.en = "Exclusive use of couchdb"
description.en = "flohmarkt expects to install CouchDB from the Apache repository for its own, exclusive use. Installation might break already existing installs of CouchDB. https://codeberg.org/ChriChri/flohmarkt_ynh/issues/9"
icon = "star-half-empty"

[arbitrary-limitations]
title.en = "Exclusive use of (sub)domain"
description.en = "flohmarkt expects to bei installed on its own (sub)domain. https://codeberg.org/ChriChri/flohmarkt_ynh/issues/4"
icon = "star-half-empty"

[arbitrary-limitations]
title.en = "No integration in yunohost user database"
description.en = "flohmarkt mainanins its own user database in CouchDB. Users have to register to flohmarkt to get an account. Registration cannot be restricted to yunohost users. https://codeberg.org/ChriChri/flohmarkt_ynh/issues/5"
icon = "star-half-empty"
