test_format = 1.0

[default]
    # still in development
	# https://codeberg.org/ChriChri/flohmarkt_ynh/issues/4
	# https://codeberg.org/ChriChri/flohmarkt_ynh/issues/11
	exclude = ["install.multi", "change_url", "install_subdir"]

    args.password_couchdb_admin = "TestPasswordCouchDBadmin"
    args.password_couchdb_flohmarkt = "TestPasswordCouchDBflohmarkt"

    test_upgrade_from.217fc0e.name = "Upgrade from ynh4"

