test_format = 1.0

[default]
    # still in development
	exclude = ["install.multi", "upgrade", "backup_restore", "change_url", "install_subdir"]

    args.password_couchdb_admin = "TestPasswordCouchDBadmin"
    args.password_couchdb_flohmarkt = "TestPasswordCouchDBflohmarkt"

