test_format = 1.0

[default]
    # changing the url of a fediverse instance doesn't make sense
    # it'll break federation anyway so we do not offer it
	exclude = ["change_url"]

    args.password_couchdb_admin = "TestPasswordCouchDBadmin"
    args.password_couchdb_flohmarkt = "TestPasswordCouchDBflohmarkt"
    args.admin_mail = "admin@example.com"

    test_upgrade_from.217fc0e.name = "Upgrade from ynh4"

