[General]
InstanceName = __FLOHMARKT_NAME__
ExternalURL = https://__DOMAIN____PATH__
HttpsNoVerifyCert = 0
JwtSecret = __JWTSECRET__
DataPath = __DATA_DIR__

[Database]
UseHttps = 0
Host = 127.0.0.1
User = __APP__
Password = __PASSWORD_COUCHDB_FLOHMARKT__
Port = 5984
Database = __APP__

[Email]
MailMethod = smtp
From = __MAIL_USER__@__MAIL_DOMAIN__

[Email.Sendmail]
SendmailExecutable = /usr/sbin/sendmail

[Email.SMTP]
Server = 127.0.0.1
Port = 587
User = __APP__
Password = __MAIL_PWD__
CAFile = /etc/ssl/certs/ca-certificates.crt
NoVerifyCert = 1

[Tilecache]
# Tile server URL for map tiles (OpenStreetMap format)
TileServerURL = https://tile.openstreetmap.org
# Maximum number of tiles to cache.
# This is roughly 200–300 MB of tile images and should be enough for a medium-sized city (10km x 10km)
TileCacheSize = 10000
