display:
  error: true
  new: true
  unchanged: false
job_defaults:
  all: {}
  browser: {}
  shell: {}
  url: {}
report:
  discord:
    embed: false
    enabled: false
    max_message_length: 2000
    subject: '{count} changes: {jobs}'
    webhook_url: ''
  email:
    enabled: true
    from: '__MAIL_USER__@__MAIL_DOMAIN__'
    html: false
    method: smtp
    sendmail:
      path: sendmail
    smtp:
      host: localhost
      auth: true
      insecure_password: '__MAIL_PWD__'
      port: 25
      starttls: true
      user: '__APP__'
    subject: 'New or deleted flohmarkt users'
    to: '__ADMIN_MAIL__'
  html:
    diff: unified
  ifttt:
    enabled: false
    event: ''
    key: ''
  mailgun:
    api_key: ''
    domain: ''
    enabled: false
    from_mail: ''
    from_name: ''
    region: us
    subject: '{count} changes: {jobs}'
    to: ''
  markdown:
    details: true
    footer: true
    minimal: false
  matrix:
    access_token: ''
    enabled: false
    homeserver: ''
    room_id: ''
  mattermost:
    enabled: false
    max_message_length: 40000
    webhook_url: ''
  pushbullet:
    api_key: ''
    enabled: false
  pushover:
    app: ''
    device: null
    enabled: false
    priority: normal
    sound: spacealarm
    user: ''
  slack:
    enabled: false
    max_message_length: 40000
    webhook_url: ''
  stdout:
    color: true
    enabled: true
  telegram:
    bot_token: ''
    chat_id: ''
    enabled: false
  text:
    details: true
    footer: true
    line_length: 75
    minimal: false
  xmpp:
    enabled: false
    recipient: ''
    sender: ''
